"""added other tables

Revision ID: d3404a805f50
Revises: 19eb9c1a5f85
Create Date: 2025-05-11 00:33:27.875023

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd3404a805f50'
down_revision: Union[str, None] = '19eb9c1a5f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('birth_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('study_participants',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('study_id', sa.UUID(), nullable=False),
                    sa.Column('participant_id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['participant_id'], ['participants.id'], ),
                    sa.ForeignKeyConstraint(['study_id'], ['studies.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('measurements',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('study_participant_id', sa.UUID(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('value', sa.Float(), nullable=False),
                    sa.Column('taken_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['study_participant_id'], ['study_participants.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    op.drop_table('study_participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
